name: Maven Central Release

on:
  release:
    types: [ created ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Update project version
        run: |
          NEW_VERSION=$(echo $GITHUB_REF | sed -e "s/refs\/tags\///")
          mvn versions:set -DnewVersion=$NEW_VERSION
          mvn versions:commit

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Build and Deploy to Maven Central
        run: mvn clean deploy -P release --settings .maven.xml
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

  update-project-version:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Update project version
        run: |
          NEW_VERSION=$(echo $GITHUB_REF | sed -e "s/refs\/tags\///")
          mvn versions:set -DnewVersion=$NEW_VERSION
          mvn versions:commit

      - name: Commit and Push
        run: |
          git config --global user.name 'zZHorizonZz'
          git config --global user.email 'danfiala23@gmail.com'
          git add pom.xml
          git commit -m "Update version to $NEW_VERSION"
          git push
